name: Python Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          source .venv/bin/activate
          python -m playwright install --with-deps

      - name: Run tests (Chromium)
        run: |
          source .venv/bin/activate
          BROWSER=chromium HEADLESS=true pytest -s --alluredir=reports/allure-results -v

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Generate Allure report
        if: always()
        run: |
          pip install allure-commandline --no-cache-dir
          allure generate reports/allure-results --clean -o reports/allure-report

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
